server:
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048
spring:
  # Internationalization
  messages:
    basename: messages/messages
  zipkin:
    baseUrl: http://localhost:9411
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    vets-service: /vet/**
    visits-service: /visit/**
    customers-service: /customer/**
    api-gateway: /gateway/**