# COMMON APPLICATION PROPERTIES
server:
  # start services on random port by default
  port: 0
  # The stop processing uses a timeout which provides a grace period during which existing requests will be allowed to complete but no new requests will be permitted
  shutdown: graceful
# embedded database init, supports mysql too trough the 'mysql' spring profile
spring:
  datasource:
    schema: classpath*:db/hsqldb/schema.sql
    data: classpath*:db/hsqldb/data.sql
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    config:
      # Allow the microservices to override the remote properties with their own System properties or config file
      allow-override: true
      # Override configuration with any local property source
      override-none: true
    # Temporary hack required by the Spring Boot 2 / Spring Cloud Finchley branch
    refresh:
      refreshable: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
# Logging
logging:
  level:
    org.springframework: INFO
# JMX Metrics
management:
  # Spring Boot 1.5 makes actuator secured by default
  security:
    enabled: false
  endpoint:
    health:
      show-details: ALWAYS
    metrics:
      enabled: true
    prometheus:
      enabled: true
  # Enable all Actuators and not only the two available by default /health and /info starting Spring Boot 2.0
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true