spring:
  zipkin:
    baseUrl: http://localhost:9411
server:
  port: 8082
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
